apiVersion: v2
name: k8s-observability-stack
description: A comprehensive monitoring and observability stack for Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: kube-prometheus-stack
    version: "45.7.1"  # Using a stable older version
    repository: https://prometheus-community.github.io/helm-charts