# K8s Observability Stack Configuration

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      retention: 30d
      scrapeInterval: 15s
      evaluationInterval: 15s
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi
      resources:
        requests:
          memory: 2Gi
          cpu: 1000m
        limits:
          memory: 4Gi
          cpu: 2000m

  grafana:
    enabled: true
    adminPassword: "ChangeMe123!"
    persistence:
      enabled: true
      size: 10Gi
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'default'
            folder: 'Custom'
            type: file
            disableDeletion: false
            updateIntervalSeconds: 10
            options:
              path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        cluster-overview:
          url: https://grafana.com/api/dashboards/7249/revisions/1/download
        node-exporter:
          url: https://grafana.com/api/dashboards/1860/revisions/1/download

  alertmanager:
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
    config:
      global:
        resolve_timeout: 5m
      route:
        group_by: ['alertname', 'cluster', 'service']
        group_wait: 10s
        group_interval: 10s
        repeat_interval: 12h
        receiver: 'slack'
      receivers:
        - name: 'slack'
          slack_configs:
            - api_url: 'YOUR_SLACK_WEBHOOK_URL'
              channel: '#alerts'
              title: 'Alert: {{ .GroupLabels.alertname }}'

loki-stack:
  loki:
    enabled: true
    persistence:
      enabled: true
      size: 50Gi
    config:
      auth_enabled: false
      server:
        http_listen_port: 3100
      limits_config:
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h
      table_manager:
        retention_deletes_enabled: true
        retention_period: 168h

  promtail:
    enabled: true
    config:
      serverPort: 3101
      clients:
        - url: http://loki:3100/loki/api/v1/push
