# Production environment configuration

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      retention: 30d
      replicas: 2
      storageSpec:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 100Gi
      resources:
        requests:
          memory: 4Gi
          cpu: 2000m
        limits:
          memory: 8Gi
          cpu: 4000m

  grafana:
    replicas: 2
    persistence:
      size: 20Gi

  alertmanager:
    alertmanagerSpec:
      replicas: 3

loki-stack:
  loki:
    replicas: 3
    persistence:
      size: 100Gi
